model = "gpt-5.2-codex"
approval_policy = "on-request"
sandbox_mode = "danger-full-access"

[features]
web_search_request = true

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]

[mcp_servers.react-native-guide]
command = "npx"
args = ["@mrnitro360/react-native-mcp-guide@1.1.0"]

[mcp_servers.svelte]
command = "npx"
args = ["-y", "@sveltejs/mcp"]

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
