apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - docker-build-push.yaml
  - docker-pipeline-mvp.yaml
  - container-tests-config.yaml
  - remediate-argocd-unhealthy.yaml
  - remediate-externalsecret-failure.yaml
  - provision-app-workflow.yaml
