apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-registry-credentials
  namespace: cicd
  labels:
    app.kubernetes.io/name: externalsecret
    app.kubernetes.io/instance: docker-registry-credentials
    app.kubernetes.io/component: secret-sync
    app.kubernetes.io/part-of: idp
    owner: platform-team
    business-unit: infrastructure
    environment: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cicd
    kind: SecretStore
  target:
    name: docker-registry-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .registry | default "docker.io" }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  dataFrom:
    - extract:
        key: secret/docker/registry
