# IDP Blueprint Demo SetUp

[cluster]
# Name of the local k3d cluster
name = "idp-demo"

[fuses]
policies = true
security = true
observability = true
cicd = true
backstage = true
# Harden profile
prod = false

[images]
docker_image_name = "roucru/idp-blueprint"
docker_image_tag = "latest"
docker_image_tag_minimal = "minimal"

[network]
# Leave lan_ip empty to auto-detect the primary interface IP.
lan_ip = ""
nodeport_http = 30080
nodeport_https = 30443

[versions]
cilium = "1.18.2"
cert_manager = "v1.19.0"
prometheus_operator_crds = "23.0.0"
gateway_api = "v1.2.1"
external_secrets = "0.20.2"
vault = "0.31.0"
argocd = "8.6.0"
argo_events = "2.4.12"
backstage = "2.6.3"


[operational]
kubectl_timeout = "300s"
k3d_config = "IT/k3d-cluster.yaml"
registry_cache_path = "$HOME/.k3d-registry"

[git]
# Optional overrides; leave empty to use the current repo/branch.
repo_url = ""
target_revision = ""
github_org = "rou-cru"
github_repo = "idp-blueprint"
github_branch = "main"

github_token = " "

[argocd]
sync_timeout = "8m"
backoff_duration = "10s"
backoff_factor = 2
backoff_max_duration = "5m"
retry_limit = 10

[gateway]
wait_timeout = "60s"

[registry]
url = "docker.io"
username = ""
password = ""
