apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: idp-security
  annotations:
    backstage.io/source-location: url:https://github.com/rou-cru/idp-blueprint/tree/main/Catalog/systems/idp-security.yaml
  description: Security System
spec:
  owner: platform-team
  domain: security
