apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cicd
  namespace: cicd
  labels:
    app.kubernetes.io/name: secretstore
    app.kubernetes.io/instance: cicd
    app.kubernetes.io/component: secret-backend
    app.kubernetes.io/part-of: idp
    owner: platform-team
    business-unit: infrastructure
    environment: demo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    description: 'SecretStore connecting to Vault for CICD secrets'
    contact: platform-team
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    vault:
      server: "https://vault.vault-system.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: Secret
        name: idp-demo-ca-secret
        namespace: cert-manager
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-cicd-role"
          serviceAccountRef:
            name: external-secrets
            audiences:
              - vault
