apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - eventbus.yaml
helmCharts:
  - name: argo-events
    repo: https://argoproj.github.io/argo-helm
    version: 2.4.12
    releaseName: argo-events
    namespace: argo-events
    valuesFile: values.yaml
