apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-component-labels
  labels:
    app.kubernetes.io/part-of: idp
    app.kubernetes.io/component: policy
    owner: platform-team
    business-unit: infrastructure
    environment: demo
  annotations:
    policies.kyverno.io/title: Require Standard Component Labels
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: 'Label, Deployment, StatefulSet, DaemonSet'
    policies.kyverno.io/description: >-
      This policy audits that all Deployments, StatefulSets, and DaemonSets include a
      standard set of component-specific labels as defined in the project's tagging
      policy. It checks for the existence of app.kubernetes.io/name,
      app.kubernetes.io/instance, app.kubernetes.io/version, and
      app.kubernetes.io/component.
spec:
  validationFailureAction: audit
  admission: true
  background: true
  emitWarning: false
  rules:
    - name: check-for-standard-component-labels
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
      skipBackgroundRequests: true
      validate:
        allowExistingViolations: true
        message:
          'Resource must include the standard component labels: app.kubernetes.io/name,
          app.kubernetes.io/instance, app.kubernetes.io/version,
          app.kubernetes.io/component.'
        pattern:
          metadata:
            labels:
              app.kubernetes.io/name: '?*'
              app.kubernetes.io/instance: '?*'
              app.kubernetes.io/version: '?*'
              app.kubernetes.io/component: '?*'
