apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8s-events
  description: Component for events in K8s
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: eventbus-default
    backstage.io/kubernetes-namespace: events
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=argo-events'
spec:
  type: service
  lifecycle: production
  owner: guests
