apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-demo-users
  namespace: backstage

data:
  users.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: admins
    spec:
      type: team
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: developers
    spec:
      type: team
      parent: admins
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: admin
    spec:
      memberOf: [admins]
      profile:
        email: admin@example.com