apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-postgresql
  namespace: backstage
  labels:
    app.kubernetes.io/name: externalsecret
    app.kubernetes.io/instance: backstage-postgres
    app.kubernetes.io/component: secret-sync
    app.kubernetes.io/part-of: idp
    owner: platform-team
    business-unit: infrastructure
    environment: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    description: 'Syncs Backstage PostgreSQL credentials from Vault KV'
    contact: platform-team
spec:
  refreshInterval: 3m
  secretStoreRef:
    name: backstage
    kind: SecretStore
  target:
    name: backstage-postgresql
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: secret
          app.kubernetes.io/instance: backstage-postgres
          app.kubernetes.io/component: credentials
          app.kubernetes.io/part-of: idp
          owner: platform-team
          business-unit: infrastructure
          environment: demo
  data:
    - secretKey: postgres-password
      remoteRef:
        key: secret/backstage/postgres
        property: adminPassword
    - secretKey: password
      remoteRef:
        key: secret/backstage/postgres
        property: appPassword
