apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-app-secrets
  namespace: backstage
  labels:
    app.kubernetes.io/name: externalsecret
    app.kubernetes.io/instance: backstage-app
    app.kubernetes.io/component: secret-sync
    app.kubernetes.io/part-of: idp
    owner: platform-team
    business-unit: infrastructure
    environment: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    description: 'Syncs Backstage backend secret and DB password from Vault KV'
    contact: platform-team
spec:
  refreshInterval: 3m
  secretStoreRef:
    name: backstage
    kind: SecretStore
  target:
    name: backstage-app-secrets
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: secret
          app.kubernetes.io/instance: backstage-app
          app.kubernetes.io/component: credentials
          app.kubernetes.io/part-of: idp
          owner: platform-team
          business-unit: infrastructure
          environment: demo
  data:
    - secretKey: BACKEND_SECRET
      remoteRef:
        key: secret/backstage/app
        property: backendSecret
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/backstage/postgres
        property: appPassword
