apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-postgresql
  namespace: backstage
  labels:
    app.kubernetes.io/part-of: idp
    app.kubernetes.io/component: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: backstage
    kind: SecretStore
  target:
    name: backstage-postgresql
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: secret/backstage/postgres
        property: adminPassword
    - secretKey: password
      remoteRef:
        key: secret/backstage/postgres
        property: appPassword
