apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-app-secrets
  namespace: backstage
  labels:
    app.kubernetes.io/part-of: idp
    app.kubernetes.io/component: developer-portal
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: backstage
    kind: SecretStore
  target:
    name: backstage-app-secrets
    creationPolicy: Owner
  data:
    # checkov:skip=CKV_SECRET_6:False positive, key name not secret value
    - secretKey: BACKEND_SECRET
      remoteRef:
        key: secret/backstage/app
        property: backendSecret
    # checkov:skip=CKV_SECRET_6:False positive, key name not secret value
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/backstage/postgres
        property: appPassword
    # checkov:skip=CKV_SECRET_6:False positive, key name not secret value
    - secretKey: DEX_CLIENT_SECRET
      remoteRef:
        key: secret/backstage/app
        property: dexClientSecret
    # checkov:skip=CKV_SECRET_6:False positive, key name not secret value
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: secret/backstage/app
        property: githubToken
    # checkov:skip=CKV_SECRET_6:False positive, key name not secret value
    - secretKey: ARGOCD_USERNAME
      remoteRef:
        key: secret/argocd/admin
        property: username
    # checkov:skip=CKV_SECRET_6:False positive, key name not secret value
    - secretKey: ARGOCD_PASSWORD
      remoteRef:
        key: secret/argocd/admin
        property: plainPassword
