apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-demo-users
  namespace: backstage
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/component: catalog
    app.kubernetes.io/part-of: idp
data:
  users.yaml: |
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: admins
      description: Administrators Group
    spec:
      type: team
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: developers
      description: Developers Group
    spec:
      type: team
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: guests
      description: Guests Group
    spec:
      type: team
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: admin
      annotations:
        # This annotation helps the resolver match the user
        google.com/email: admin@example.com
    spec:
      profile:
        displayName: Admin User
        email: admin@example.com
        picture: https://avatars.dicebear.com/api/avataaars/admin.svg
      memberOf: [admins, developers]
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: developer
      annotations:
        google.com/email: developer@example.com
    spec:
      profile:
        displayName: Developer User
        email: developer@example.com
        picture: https://avatars.dicebear.com/api/avataaars/developer.svg
      memberOf: [developers]
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: guest
      annotations:
        google.com/email: guest@example.com
    spec:
      profile:
        displayName: Guest User
        email: guest@example.com
        picture: https://avatars.dicebear.com/api/avataaars/guest.svg
      memberOf: [guests]
