apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: backstage
    repo: https://backstage.github.io/charts
    version: 2.6.3
    releaseName: backstage
    namespace: backstage
    valuesFile: values.yaml

resources:
  - vars-placeholder.yaml
  - cm-placeholder.yaml
  - ca-cert-configmap.yaml
  - job-renderer.yaml
  - sync-ca-cert-job.yaml
  - backstage-app-externalsecret.yaml

  - backstage-postgres-externalsecret.yaml
  - backstage-demo-users.yaml
  - templates/cm-tpl.yaml
