apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: backstage
    repo: https://backstage.github.io/charts
    version: 2.6.3
    releaseName: backstage
    namespace: backstage
    valuesFile: values.yaml

resources:
  - backstage-app-externalsecret.yaml
  - backstage-postgres-externalsecret.yaml
  - service-monitor.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: idp
      owner: platform-team
      business-unit: infrastructure
      environment: demo
