apiVersion: v1
kind: ResourceQuota
metadata:
  name: observability-quota
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: idp
    app.kubernetes.io/component: governance
    owner: platform-team
    business-unit: infrastructure
    environment: demo
spec:
  hard:
    requests.cpu: "800m"
    requests.memory: "2Gi"
    limits.cpu: "2500m"
    limits.memory: "4Gi"
