apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: backstage
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: eso-backstage
    app.kubernetes.io/component: secret-sync
    app.kubernetes.io/part-of: idp
    owner: platform-team
    business-unit: infrastructure
    environment: demo
  annotations:
    description: 'ESO ServiceAccount for secret synchronization from Vault'
    contact: platform-team
    documentation: https://external-secrets.io