apiVersion: v1
kind: Namespace
metadata:
  name: security
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/part-of: idp
    business-unit: infrastructure
    owner: platform-team
    environment: demo
