apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  contact: platform-team
  documentation: https://github.com/rou-cru/idp-blueprint

resources:
  - cert-manager/
  - argocd/
  - external-secrets/
  - serviceaccounts/
  - gateway/

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: idp
      owner: platform-team
      business-unit: infrastructure
      environment: demo
