apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ca-secret-reader-rbac.yaml
  - argocd-secretstore.yaml
  - argocd-admin-externalsecret.yaml

commonAnnotations:
  contact: platform-team
  documentation: https://external-secrets.io

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: idp
      business-unit: infrastructure
      environment: demo
      owner: platform-team
