apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: security
  description: Security Infrastructure Resources
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: trivy-operator
    backstage.io/kubernetes-namespace: security
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/name=trivy-operator"
spec:
  type: kubernetes
  lifecycle: production
  owner: platform-team
  system: idp
