apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: dex
    repo: https://charts.dexidp.io
    version: 0.19.0
    releaseName: dex
    namespace: backstage
    valuesFile: values.yaml

resources:
  - dex-externalsecret.yaml
  - templates/cm-tpl.yaml
  - secret-placeholder.yaml
  - job-renderer.yaml
  - vars-placeholder.yaml

