apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - dex-serviceaccount.yaml
  - dex-config.yaml
  - dex-deployment.yaml
  - dex-service.yaml
  - dex-ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: idp
  owner: platform-team
  business-unit: infrastructure
  environment: demo

# DNS_SUFFIX is replaced via envsubst at deployment time
# Usage: kustomize build K8s/backstage/dex | envsubst | kubectl apply -f -
