apiVersion: v1
kind: Secret
metadata:
  name: dex
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
stringData:
  config.yaml: |
    # PLACEHOLDER: This content will be replaced by the dex-config-renderer job
    issuer: https://dex.placeholder.local
