apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all namespace definitions to be applied.
resources:
  - argocd.yaml
  - argo-events.yaml
  - backstage.yaml
  - cert-manager.yaml
  - cicd.yaml
  - external-secrets-system.yaml
  - observability.yaml
  - vault-system.yaml
