apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: policies
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: idp
    app.kubernetes.io/component: applicationset
    owner: platform-team
    business-unit: infrastructure
    environment: demo
spec:
  generators:
    - git:
        repoURL: ${REPO_URL}
        revision: ${TARGET_REVISION}
        directories:
          - path: K8s/policies/*
  template:
    metadata:
      name: 'policies-{{path.basename}}'
    spec:
      project: policies
      source:
        repoURL: ${REPO_URL}
        targetRevision: ${TARGET_REVISION}
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: kyverno-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m
