apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: gateway-service-patch.yaml
    target:
      kind: Service
      name: cilium-gateway-idp-gateway
      namespace: kube-system
