apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: argo-workflows-controller-availability
  namespace: observability
  labels:
    app.kubernetes.io/part-of: idp
    app.kubernetes.io/component: slo
    app.kubernetes.io/name: argo-workflows-controller
    app.kubernetes.io/instance: argo-workflows-demo
    owner: platform-team
    business-unit: infrastructure
    environment: demo
    tier: critical
spec:
  target: "99.0"
  window: 6h
  description: "Argo Workflows Controller should operate without internal panics or submission errors"
  indicator:
    ratio:
      errors:
        metric: argo_workflows_error_count{cause=~"OperationPanic|CronWorkflowSubmissionError"}
      total:
        metric: argo_workflows_k8s_request_total
