apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  # Apply SLO CRs after Pyrra is in place
  argocd.argoproj.io/sync-wave: "3"

resources:
  - secrets-sync-slo.yaml
  - loki-ingest-availability-slo.yaml
  - gateway-api-availability-slo.yaml
  - vault-api-availability-slo.yaml
