apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: externalsecrets-sync-success
  namespace: observability
  labels:
    app.kubernetes.io/part-of: idp
    app.kubernetes.io/component: slo
    app.kubernetes.io/name: externalsecrets-sync
    app.kubernetes.io/instance: externalsecrets-sync-demo
    owner: platform-team
    business-unit: infrastructure
    environment: demo
spec:
  target: "97.0"
  window: 6h
  indicator:
    ratio:
      errors:
        metric: externalsecret_sync_calls_total{result!~"success|succeeded"}
      total:
        metric: externalsecret_sync_calls_total
      grouping:
        - name
        - namespace
