apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: vault-api-availability
  namespace: observability
  labels:
    app.kubernetes.io/part-of: idp
    app.kubernetes.io/component: slo
    app.kubernetes.io/name: vault-api-availability
    app.kubernetes.io/instance: vault-api-demo
    owner: platform-team
    business-unit: infrastructure
    environment: demo
    tier: critical
spec:
  target: "97.0"
  window: 6h
  description: "Vault API should successfully handle secret requests"
  indicator:
    ratio:
      errors:
        metric: vault_core_handle_request_count{status="failure"}
      total:
        metric: vault_core_handle_request_count
