apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cicd
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: idp
    app.kubernetes.io/component: applicationset
    owner: platform-team
    business-unit: infrastructure
    environment: demo
spec:
  generators:
    - git:
        repoURL: ${REPO_URL}
        revision: ${TARGET_REVISION}
        directories:
          - path: K8s/cicd/*
  template:
    metadata:
      name: "cicd-{{path.basename}}"
    spec:
      project: cicd
      source:
        repoURL: ${REPO_URL}
        targetRevision: ${TARGET_REVISION}
        path: "{{path}}"
        kustomize: {}
      destination:
        server: https://kubernetes.default.svc
        namespace: cicd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 10
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 10m
      ignoreDifferences:
        - group: ""
          kind: Secret
          jsonPointers:
            - /data
            - /metadata/labels
        - group: ""
          kind: ServiceAccount
          jsonPointers:
            - /secrets
