apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8s-argocd
  description: Component for argocd in K8s
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: argocd
    backstage.io/kubernetes-namespace: argocd
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=argocd'
spec:
  type: service
  lifecycle: production
  owner: guests
