---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-admin-credentials
  namespace: cicd
  labels:
    app.kubernetes.io/name: externalsecret
    app.kubernetes.io/instance: sonarqube-admin
    app.kubernetes.io/component: secret-sync
    app.kubernetes.io/part-of: idp
    owner: platform-team
    business-unit: infrastructure
    environment: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    description: 'Syncs SonarQube admin credentials from Vault KV'
    contact: 'platform-team'
    documentation: 'https://external-secrets.io/latest/api/externalsecret/'
spec:
  refreshInterval: 3m0s
  secretStoreRef:
    name: cicd
    kind: SecretStore
  target:
    name: sonarqube-admin-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/name: secret
          app.kubernetes.io/instance: sonarqube-admin
          app.kubernetes.io/component: credentials
          app.kubernetes.io/part-of: idp
          owner: platform-team
          business-unit: infrastructure
          environment: demo
      data:
        password: '{{ .password }}'
        currentPassword: admin
  dataFrom:
    - extract:
        key: secret/sonarqube/admin
