apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage
  description: Backstage Infrastructure Resources
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: backstage
    backstage.io/kubernetes-namespace: backstage
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/name=backstage"

spec:
  type: kubernetes
  lifecycle: production
  owner: platform-team
  system: idp

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: idp
  description: Internal Developer Platform System
spec:
  owner: platform-team
