apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-application-controller
  description: Kubernetes controller that continuously monitors running applications.
  tags: [controller, k8s, tier-critical, environment-demo, platform-infrastructure]
  annotations:
    backstage.io/source-location: url:https://github.com/rou-cru/idp-blueprint/tree/main/Catalog/components/argocd-application-controller.yaml
    backstage.io/kubernetes-id: argocd-application-controller
    backstage.io/kubernetes-namespace: argocd
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/name=argocd-application-controller"
    # Kyverno Policy Reporter
    kyverno.io/namespace: argocd
    kyverno.io/kind: StatefulSet
    kyverno.io/resource-name: argocd-application-controller
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: idp-orchestration
  subComponentOf: argocd
  dependsOn:
    - resource:default/local-k8s-cluster
    - resource:argocd-redis
