apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.appName }}
  title: ${{ values.appName }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repoUrl | replace('https://github.com/', '') }}
    backstage.io/kubernetes-id: ${{ values.appName }}
    backstage.io/kubernetes-namespace: ${{ values.appName }}
    argocd/app-name: ${{ values.appName }}
    backstage.io/techdocs-ref: dir:.
  labels:
    app.kubernetes.io/name: ${{ values.appName }}
    app.kubernetes.io/part-of: user-applications
    owner: ${{ values.owner }}
    business-unit: ${{ values.businessUnit }}
    environment: ${{ values.environment }}
  tags:
    - containerized
    - ${{ values.environment }}
    - self-service
  links:
    - url: ${{ values.repoUrl }}
      title: Source Repository
      icon: github
    - url: https://argocd.${DNS_SUFFIX}/applications/${{ values.appName }}
      title: ArgoCD Application
      icon: dashboard
    - url: https://${{ values.appName }}.${DNS_SUFFIX}
      title: Application URL
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  system: idp
  providesApis: []
  consumesApis: []
  dependsOn: []
